language: php

matrix:
  include:
    - php: 7.0
      env:
        - PHPUNIT_VERSION=6.*
    - php: 7.1
      env:
        - PHPUNIT_VERSION=6.*
    - php: 7.1
      env:
        - PHPUNIT_VERSION=7.*
    - php: 7.2
      env:
        - PHPUNIT_VERSION=6.*
    - php: 7.2
      env:
        - PHPUNIT_VERSION=7.*

install:
  - composer require phpunit/phpunit:$PHPUNIT_VERSION;
